### ISSUE TITLE
plotPGMM : 'x' and 'y' lengths differ

### ISSUE THREAD

**Issue by raim** [lockEF/BayesianPGMM#1]
when trying to use plotPGMM with my own data, I get the error:
Error in xy.coords(x, y) : 'x' and 'y' lengths differ

I tracked the problem to the lenght of xvec in the plotPGMM function, which
is fixed at 100. Changing this to M, both in initialization of xvec and in the loop 
(for (j in 1:100)) seemed to fix the problem.

(The plot shows three expected segments for my data, but both the breakpoints and slopes 
seem wrong, but that's a different issue)

**Comment by lockEF** [comment]
Thanks for the comment.  I have fixed an issue with the initialization of Clus_mean[[k]], on line 36 of plotPGMM -- it should initializing to a vector of length 100 rather than length M.  However, I was unable to reproduce the error,  and I am not sure if this fixes the issue.   Please let me know if you encounter the same error.  

Here, 'xvec' are the time points to evaluate the mean trajectory, and are spaced densely (at 100 values over the time range) to show the precise location of the estimated changepoints. Its length need not equal M (the number of measurement occasions), in general.
